merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/',views.band_detail,name='band-detail'),
    path('bands/add/',views.band_create,name='band-create'),
    path('bands/<int:id>/change/',views.band_update,name='band-update'),
    path('bands/<int:id>/delete/',views.band_delete,name='band-delete'),
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:id>/', views.listing_detail,name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:id>/change/', views.listing_update, name='listing-update'),
    path('listings/<int:id>/delete/', views.listing_delete, name='listing-delete'),
    path('about-us/', views.about, name='about-us'),
    path('contact-us/', views.contact,name='contact'),
 
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2021)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class Listing(models.Model):

    class Type(models.TextChoices):
        disques   = 'Records'
        vêtements = 'Clothing'
        affiches  = 'Posters'
        divers    = 'Miscellaneous'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=255)
    sold = models.fields.BooleanField(default=True)
    year = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2021)], blank=True)
    type = models.fields.CharField(choices=Type.choices, max_length=15)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return f'{self.title}'

merchex/listings/forms.py
from django import forms
from listings.models import Band ,Listing


class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):

   class Meta:
      model = Band
      fields = '__all__'


class ListingForm(forms.ModelForm):

   class Meta:
      model = Listing
      fields = '__all__'

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band,Listing
from listings.forms import ContactUsForm,BandForm, ListingForm
from django.core.mail import send_mail
from django.shortcuts import redirect

def band_list(request):
    bands = Band.objects.all()
    return render(request,'listings/band_list.html',{'bands':bands})

def band_detail(request,id):
    band = Band.objects.get(id=id)
    return render(request,'listings/band_detail.html',{'band':band})

def band_create(request):

    if request.method == 'POST':

        form = BandForm(request.POST)

        if form.is_valid():
                
            band = form.save()
            
            return redirect('band-detail',band.id)
    
    else :
        
        form = BandForm()

    return render(request,'listings/band_create.html',{'form':form})


def band_update(request,id):

    band = Band.objects.get(id=id)

    if request.method =='POST':

        form = BandForm(request.POST, instance=band)

        if form.is_valid():

            form.save()

            return redirect('band-detail',band.id)
        
    else :

        form = BandForm(instance=band)

    return render(request,'listings/band_update.html',{'form':form})

def band_delete(request,id):

    band = Band.objects.get(id=id)

    if request.method =='POST':

        band.delete()

        return redirect('band-list')
        

    return render(request,'listings/band_delete.html',{'band':band})


def listing_list(request):
    listings = Listing.objects.all()
    return render(request, 'listings/listing_list.html',{'listings':listings})

def listing_detail(request,id):
    listing = Listing.objects.get(id=id)
    return render(request,'listings/listing_detail.html',{'listing':listing})

def listing_create(request):

    if request.method =='POST':
         
        form = ListingForm(request.POST)

        if form.is_valid() :

            listing = form.save()

            return redirect('listing-detail', listing.id)
    else :

        form = ListingForm()

    return render(request, 'listings/listing_create.html',{'form':form})

def listing_update(request,id):

    listing = Listing.objects.get(id=id)   

    if request.method == 'POST':

        form = ListingForm(request.POST, instance=listing)

        if form.is_valid():
             
             form.save()
             return redirect('listing-detail',listing.id)
    else :
         
         form = ListingForm(instance=listing)

    return render(request,'listings/listing_update.html',{'form':form})

def listing_delete(request,id):

    listing = Listing.objects.get(id=id)

    if request.method =='POST':

        listing.delete()

        return redirect('listing-list')
        

    return render(request,'listings/listing_delete.html',{'listing':listing})



def about(request):
    return render(request, 'listings/about-us.html')

def contact(request):

    if request.method == 'POST':
       
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
            subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['shalombaigodari@gmail.com'],)

            return redirect('contact')

    else:

        form = ContactUsForm()

    return render(request,'listings/contact.html',{'form': form})

merchex/listings/templates/listings/about-us.html
{% extends 'listings/base.html'%}
{% block content %}
    <h1>A propos</h1>
{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html'%}
{%block content%}
<h1>Créer un nouveau groupe</h1>
<form action="" method="post" >
    {%csrf_token%}
    {{form}}
    <button type="submit">Enregistrer</button>
</form>

{%endblock%}

merchex/listings/templates/listings/band_delete.html
{%extends 'listings/base.html'%}
{%block content%}
<h1>Suppresion le  groupe : </h1>
<p>Etes-vous sure de vouloir supprimer le groupe :{{band.name}} ?</p>
<form action="" method="post">
    {%csrf_token%}
    <button type="submit">Supprimer</button>
</form>
{%endblock%}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active|yesno }}</li>
 {% if band.official_homepage %}
 <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
 {% endif %}

 {% for listing in band.listing_set.all %}
 <li>Band : {{listing}} </li>
 {%endfor%}
 
</ul>

<p>{{ band.biography }}</p>
<a href="{% url 'band-update' band.id%}">Modifier</a>
<a href="{% url 'band-delete' band.id%}">Supprimmer</a>
<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}
{% block content %}
<h1>Groupes</h1>
<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
<ul>
    {% for band in bands %}
    <li><a href="{% url 'band-detail' band.id %}">{{band.name }}</a>
        - <a href="{% url 'band-update' band.id %}">[modifier]</a>
    </li>
    {%endfor%}
</ul>   
{% endblock %}

merchex/listings/templates/listings/band_update.html
{%extends 'listings/base.html'%}
{%block content%}
    <h1>Mise à jour du groupe</h1>
    <form action="" method="post">
        {%csrf_token%}
        {{form}}
        <button type="submit">Mettre à jour</button>
    </form>
{%endblock%}

merchex/listings/templates/listings/base.html
{% load static %}
<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/style.css' %}"/>
    </head>
    <body>
        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
            <a href="{% url 'listing-list' %}">Listings</a>
            <a href="{% url 'about-us' %}">A propos</a>
            <a href="{% url 'contact' %}">Contact</a>
        </nav>

        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html'%}

{% block content %}
    <h1>Contactez-nous</h1>
    <p>Nous sommes là pour vous aider.</p>

    <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Envoyer">
    </form>
{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html'%}
{%block content%}

<h1>Créer un nouveau listing</h1>

<form action="{% url 'listing-create' %}" method="post">
    {%csrf_token%}
    {{form}}
    <button type="submit">Envoyer</button>
</form>


{%endblock%}

merchex/listings/templates/listings/listing_delete.html
{%extends 'listings/base.html'%}
{%block content%}
<h1>Suppresion le  listing : </h1>
<p>Etes-vous sure de vouloir supprimer le listing :{{listing.title}} ?</p>
<form action="" method="post">
    {%csrf_token%}
    <button type="submit">Supprimer</button>
</form>
{%endblock%}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}
{%block content %}
<h2>{{listing.title}}</h2>
<ul>
        {% if listing.description %}
        <li>Description : {{ listing.description }}</li>
        {%endif%}
        <li>Sold : {{ listing.sold |yesno}}</li>
        <li>Type : {{ listing.get_type_display }}</li>
        <li>year : {{ listing.year }}</li>
       
</ul>
<a href="{%url 'listing-update' listing.id %}">Modifier</a>
<a href="{%url 'listing-delete' listing.id %}">Supprimer</a>
<a href="{% url 'listing-list' %}">Retour à tous les listings</a>
{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html'%} 
{% block content %}
        <p>Listings :</p>
        <a href="{% url 'listing-create'%}">Créer un nouveau listing</a>
        <ul>
            {%for listing in listings%}
            <li><a href="{% url 'listing-detail' listing.id %}">{{listing.title }}</a>
                -<a href="{% url 'listing-update' listing.id %}">[modifier]</a>
            </li>
            {%endfor%}
        </ul>
{% endblock %}

merchex/listings/templates/listings/listing_update.html
{%extends 'listings/base.html'%}
{%block content%}
<h1>Mise à jour listing : </h1>
<form action="" method="post">
    {%csrf_token%}
    {{form}}
    <button type="submit">modifier</button>
</form>
{%endblock%}